-- source this script from mySQL

use blue;

-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 10:54:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blue
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blue
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blue` DEFAULT CHARACTER SET utf8 ;
USE `blue` ;

-- -----------------------------------------------------
-- Table `blue`.`parkings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue`.`parkings` (
  `id_parking` INT NOT NULL AUTO_INCREMENT,
  `parking_name` VARCHAR(45) NULL,
  `capacity_bike` INT NULL,
  `capacity_car` INT NULL,
  `capacity_camper` INT NULL,
  `cost_bike` DECIMAL(6,2) NOT NULL,
  `cost_car` DECIMAL(6,2) NOT NULL,
  `cost_camper` DECIMAL(6,2) NOT NULL,
  `capacity_electric_vehicle` INT NULL,
  `cost_electric_vehicle` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id_parking`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blue`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue`.`vehicles` (
  `vehicle_id` INT NOT NULL,
  `vehicle_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vehicle_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blue`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `credit` DECIMAL(6,2) NOT NULL,
  `vehicle_id` INT NULL,
  `license_plate` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `car_id_UNIQUE` (`vehicle_id` ASC) VISIBLE,
  UNIQUE INDEX `license_plate_UNIQUE` (`license_plate` ASC) VISIBLE,
  CONSTRAINT `vehicle_id`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `blue`.`vehicles` (`vehicle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blue`.`parking_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue`.`parking_history` (
  `id_parking_history` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `id_parking` INT NULL,
  PRIMARY KEY (`id_parking_history`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_parking_idx` (`id_parking` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `blue`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_parking`
    FOREIGN KEY (`id_parking`)
    REFERENCES `blue`.`parkings` (`id_parking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
parking_history